exp_name: recover

data:
  mixture_index_dir: datasets/lrs3
  clean_audio_dir: datasets/lrs3/audio
  visual_feature_dir: datasets/lrs3/video_processed
  train_file: mix_2_spk_train_fully_overlapped_only_6000.txt
  valid_file: mix_2_spk_valid_fully_overlapped_only_2000.txt
  test_file: mix_2_spk_test_fully_overlapped_only_3000.txt

train:
  num_blocks: 8
  need_train: True
  model_config: avlit_default
  loss_config: PermInvariantSISDR_Train
  batch_size: 16
  reference_type: null
  reference_drop_rate: 0
  sampling_rate: 16000
  max_epoch: 100
  lr: 0.001
  weight_decay: 0.1
  num_chunks: 5
  recover_weight: 0.05